---
- name: create test config file
  template:
    src: ipa-test-config.yaml
    dest: /vagrant/ipa-test-config.yaml
  when: inventory_hostname == 'controller'

- name: add PR build repository
  get_url:
    dest: /etc/yum.repos.d/
    url: "{{ repofile_url }}"

# This works as long as the version to be tested is newer than what's
# available in the distro repositories
- name: install freeipa packages
  dnf:
    name: "{{ item }}"
    state: latest
  with_items:
    - freeipa-*
    - python*-ipatests

- name: get all packages
  shell: rpm -qa
  register: packages

- name: display installed packages
  debug:
    var: packages.stdout

- name: create hosts file from template
  template:
    src: hosts
    dest: /etc/hosts

- name: create /etc/resolv.conf file from template
  template:
    src: resolv.conf
    dest: /etc/resolv.conf

# - name: set hostname
#   hostname:
#     name: "{{ inventory_hostname }}.ipa.test"

# workaround for https://github.com/ansible/ansible/issues/19814
- name: set hostname
  shell: "hostnamectl set-hostname {{ inventory_hostname }}.ipa.test"
