---
- name: create config directory if it dosn't exist
  file:
    path: /root/.config/freeipa-pr-ci
    state: directory
    owner: root
    group: root
    mode: 0700

- name: copy github credentials file
  template:
    src: credentials.yaml
    dest: /root/.config/freeipa-pr-ci/credentials.yaml
