---
- name: clone FreeIPA PR CI repo
  git: 
    dest: /root/freeipa-pr-ci
    repo: "{{ freeipa_pr_ci_repo }}"
    version: master
    force: true

- name: install python dependencies with pip
  pip:
    requirements: /root/freeipa-pr-ci/requirements.txt
    executable: pip3
    extra_args: --upgrade
    state: present

- name: create systemd unit for prci
  copy:
    src: prci.service
    dest: /etc/systemd/system/prci.service
  notify:
    - systemd_daemon_reload
    - enable_prci
  when: create_systemd_unit
