---
- name: clone FreeIPA PR CI repo
  git: 
    dest: /root/freeipa-pr-ci
    repo: https://github.com/tomaskrizek/freeipa-pr-ci
    version: master
    force: true

- name: install python dependencies with pip
  pip:
    requirements: /root/freeipa-pr-ci/requirements.txt
    executable: pip3
    state: present
