---
- name: "make sure {{ ssh_key_dir }} exists"
  file:
    path: "{{ ssh_key_dir }}"
    state: directory
    mode: 0700

- name: "add freeipa_pr_ci private key"
  copy:
    src: ../keys/freeipa_pr_ci
    dest: "{{ ssh_key_dir }}/freeipa_pr_ci"
    mode: 0600
