---
- name: enable nfs
  service:
    name: nfs
    enabled: true

# Workaround for bug in lab -- dnf makecache created metadata lock
- name: "workaround: stop dnf-makecache.service"
  service:
    name: dnf-makecache.service
    state: stopped

- name: install runner dependencies
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - vagrant
    - vagrant-libvirt
    - libguestfs-tools-c  # required for vagrant package command
    - ansible  # TODO requires >= 2.3 
    - nfs-utils
    - git
    - libvirt
    - rsync
    - createrepo
    - gzip
    - gcc
    - python3-devel
    - python3-pip
    - redhat-rpm-config
  notify:
    - restart_nfs

- name: start&enable libvirt services
  service:
    name: "{{ item }}"
    enabled: true
    state: started
  with_items:
    - virtlogd
    - libvirtd
