---
- name: enable nfs
  service:
    name: nfs
    enabled: true

- name: install runner dependencies
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - vagrant
    - vagrant-libvirt
    - libguestfs-tools-c  # required for vagrant package command
    - ansible  # TODO requires >= 2.3 
    - nfs-utils
    - git
    - libvirt
    - python-github3
    - rsync
    - python-jinja2
    - createrepo
    - gzip
  notify:
    - restart_nfs

- name: start&enable libvirt services
  service:
    name: "{{ item }}"
    enabled: true
    state: started
  with_items:
    - virtlogd
    - libvirtd
