---
- name: "install runner dependencies"
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - vagrant
    - vagrant-libvirt
    - libguestfs-tools-c  # required for vagrant package command
    - ansible
    - nfs-utils
    - git
    - libvirt

