---
- name: remove any artifcats from previous packaging
  file:
    path: /tmp/image/_tmp_package
    state: absent
  tags:
    - package_box

# Turn template VM off and on again. Created vagrant box may not boot if 
# this step is omitted.
- name: shutdown template VM
  shell: vagrant halt
  args:
    chdir: /tmp/image

- name: boot template VM
  shell: vagrant up
  args:
    chdir: /tmp/image

- name: "create vagrant box"
  become_user: root
  become: yes
  # TODO replace hardcoded name with variable
  shell: vagrant package --output ipa-master-f25.box
  args:
    chdir: /tmp/image
  tags:
    - package_box

- name: change ownership of box
  become: true
  file:
    path: "/tmp/image/{{ template_box_name }}"
    owner: "{{ ansible_effective_user_id }}"
    group: "{{ ansible_effective_group_id }}"

- name: destroy template VM
  shell: vagrant destroy
  args:
    chdir: /tmp/image
