ad_admin_name: Administrator
ad_admin_password: Secret123456
admin_name: admin
admin_password: Secret.123
debug: false
dirman_dn: cn=Directory Manager
dirman_password: Secret.123
dns_forwarder: 10.34.78.1
domains:
- hosts:
  - external_hostname: master.ipa.test
    ip: 192.168.101.101
    name: master.ipa.test
    role: master
  - external_hostname: replica1.ipa.test
    ip: 192.168.101.102
    name: replica1.ipa.test
    role: replica
  - external_hostname: replica2.ipa.test
    ip: 192.168.101.103
    name: replica2.ipa.test
    role: replica
  - external_hostname: client1.ipa.test
    ip: 192.168.101.104
    name: client1.ipa.test
    role: client
  name: ipa.test
  type: IPA
nis_domain: ipatest
ntp_server: 1.pool.ntp.org
root_ssh_key_filename: /root/.ssh/freeipa_pr_ci_insecure
test_dir: ../../ipatests
